name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          repository: zingi/random-lon-lat-generator

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.50.0'
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install cc linker
        run: sudo apt-get update -y && sudo apt-get install gcc -y

      - name: Build wasm
        run: |
          ls -la && wasm-pack build && echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./pkg/*